### ISSUE TITLE
Tempo opeator shows error logs for gateway reconciliation

### ISSUE THREAD

**Issue by pavolloffay** [os-observability/tempo-operator#251]
```
1.6770695641122491e+09	INFO	Resource has been unchanged	{"controller": "microservices", "controllerGroup": "tempo.grafana.com", "controllerKind": "Microservices", "Microservices": {"name":"simplest","namespace":"ploffay"}, "namespace": "ploffay", "name": "simplest", "reconcileID": "16576549-dbe0-4614-8dc9-4a9398490989", "tempo": "ploffay/simplest", "object_name": "tempo-simplest-gateway", "object_kind": "&TypeMeta{Kind:,APIVersion:,}"}
1.6770695641123738e+09	INFO	Resource has been unchanged	{"controller": "microservices", "controllerGroup": "tempo.grafana.com", "controllerKind": "Microservices", "Microservices": {"name":"simplest","namespace":"ploffay"}, "namespace": "ploffay", "name": "simplest", "reconcileID": "16576549-dbe0-4614-8dc9-4a9398490989", "tempo": "ploffay/simplest", "object_name": "tempo-simplest-gateway", "object_kind": "&TypeMeta{Kind:,APIVersion:,}"}
1.6770695641125278e+09	INFO	Resource has been unchanged	{"controller": "microservices", "controllerGroup": "tempo.grafana.com", "controllerKind": "Microservices", "Microservices": {"name":"simplest","namespace":"ploffay"}, "namespace": "ploffay", "name": "simplest", "reconcileID": "16576549-dbe0-4614-8dc9-4a9398490989", "tempo": "ploffay/simplest", "object_name": "tempo-simplest-gateway", "object_kind": "&TypeMeta{Kind:,APIVersion:,}"}
1.6770695641126094e+09	ERROR	failed to configure resource	{"controller": "microservices", "controllerGroup": "tempo.grafana.com", "controllerKind": "Microservices", "Microservices": {"name":"simplest","namespace":"ploffay"}, "namespace": "ploffay", "name": "simplest", "reconcileID": "16576549-dbe0-4614-8dc9-4a9398490989", "tempo": "ploffay/simplest", "object_name": "tempo-simplest-gateway", "object_kind": "&TypeMeta{Kind:,APIVersion:,}", "error": "MutateFn cannot mutate object name and/or object namespace"}
github.com/os-observability/tempo-operator/controllers/tempo.(*MicroservicesReconciler).reconcileManifests
	/workspace/controllers/tempo/microservices_controller.go:190
github.com/os-observability/tempo-operator/controllers/tempo.(*MicroservicesReconciler).Reconcile
	/workspace/controllers/tempo/microservices_controller.go:92
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234
1.6770695641127136e+09	ERROR	failed to configure resource	{"controller": "microservices", "controllerGroup": "tempo.grafana.com", "controllerKind": "Microservices", "Microservices": {"name":"simplest","namespace":"ploffay"}, "namespace": "ploffay", "name": "simplest", "reconcileID": "16576549-dbe0-4614-8dc9-4a9398490989", "tempo": "ploffay/simplest", "object_name": "tempo-simplest-gateway", "object_kind": "&TypeMeta{Kind:,APIVersion:,}", "error": "MutateFn cannot mutate object name and/or object namespace"}
github.com/os-observability/tempo-operator/controllers/tempo.(*MicroservicesReconciler).reconcileManifests
	/workspace/controllers/tempo/microservices_controller.go:190
github.com/os-observability/tempo-operator/controllers/tempo.(*MicroservicesReconciler).Reconcile
	/workspace/controllers/tempo/microservices_controller.go:92
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234
1.677069564112913e+09	INFO	Resource has been unchanged	{"controller": "microservices", "controllerGroup": "tempo.grafana.com", "controllerKind": "Microservices", "Microservices": {"name":"simplest","namespace":"ploffay"}, "namespace": "ploffay", "name": "simplest", "reconcileID": "16576549-dbe0-4614-8dc9-4a9398490989", "tempo": "ploffay/simplest", "object_name": "tempo-simplest-gateway", "object_kind": "&TypeMeta{Kind:,APIVersion:,}"}
1.6770695641178575e+09	INFO	Resource has been updated	{"controller": "microservices", "controllerGroup": "tempo.grafana.com", "controllerKind": "Microservices", "Microservices": {"name":"simplest","namespace":"ploffay"}, "namespace": "ploffay", "name": "simplest", "reconcileID": "16576549-dbe0-4614-8dc9-4a9398490989", "tempo": "ploffay/simplest", "object_name": "tempo-simplest-gateway", "object_kind": "&TypeMeta{Kind:,APIVersion:apps/v1,}"}
1.677069564127366e+09	ERROR	Reconciler error	{"controller": "microservices", "controllerGroup": "tempo.grafana.com", "controllerKind": "Microservices", "Microservices": {"name":"simplest","namespace":"ploffay"}, "namespace": "ploffay", "name": "simplest", "reconcileID": "16576549-dbe0-4614-8dc9-4a9398490989", "error": "failed to create objects for Tempo ploffay/simplest"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234
```

deployed on CRC with:

```yaml
kubectl apply -f - <<EOF
apiVersion: tempo.grafana.com/v1alpha1
kind: Microservices
metadata:
  name: simplest
spec:
  storage:
    secret: minio-test
  storageSize: 1Gi
  resources:
    total:
      limits:
        memory: 2Gi
        cpu: 2000m
  tenants:
    mode: openshift
    authentication:
      - tenantName: dev
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa"
      - tenantName: production
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfb"
    authorization:
      roleBindings:
      - name: read-write
        roles:
          - read-write-traces
        subjects:
          - kind: user
            name: system:serviceaccount:ploffay:dev-collector
          - kind: user
            name: system:serviceaccount:ploffay:production-collector
          - kind: user
            name: kubeadmin
      roles:
      - name: read-write-traces
        permissions:
          - read
          - write
        resources: 
          - traces
        tenants:
          - dev
          - production
  template:
    gateway:
      enabled: true
    queryFrontend:
      jaegerQuery:
        enabled: true
EOF
```
