### ISSUE TITLE
Jaeger query ports should not be exposed if jaeger-query is disabled

### ISSUE THREAD

**Issue by pavolloffay** [os-observability/tempo-operator#77]
```
kubectl apply -f - <<EOF
apiVersion: tempo.grafana.com/v1alpha1
kind: Microservices
metadata:
  name: simplest
spec:
  limits:
    global: {}
    perTenant: {}
  retention:
    global: {}
    perTenant: {}
  storage:
    secret: test
EOF
```

```
tempo-simplest-query-frontend             ClusterIP   10.106.215.239   <none>        3100/TCP,9095/TCP,16686/TCP,16687/TCP            3m52s
tempo-simplest-query-frontend-discovery   ClusterIP   10.97.166.203    <none>        3100/TCP,9095/TCP,16686/TCP,16687/TCP,9096/TCP   3m52s
```

I am also not sure if the discovery service should expose the Jaeger ports
